# -*- coding: utf-8 -*-
"""capstone_multi_attribute_regression_vit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G10mncrnRoUZxKguSqUrIQ_-wGBEfAqV
"""

from utils.custom_dataset import *
from utils.train_functions import train_multi
from utils.test_functions import *
from utils.norm_functions import create_normalization_fns
from utils.dict import *
from utils.weightedMSE import *
from utils.clipped_relu import *
# https://docs.google.com/spreadsheets/d/1nPboUffa_6YIqomErZGAq7gbrEh0IMpBtUOL5X80Pew/edit?gid=220433975#gid=220433975
import argparse
import torch
from torchvision import models
from torchvision.io import read_image
from torch import nn
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
from tqdm import tqdm
from torchvision import transforms

'''
Hyper parameters

'''
# for now: shirt, skirt, pants, waistband
# name = "skirt"

# learning_rate = 0.0005
# epochs = 100
# n_stop = 20
# batch_size = 8
#penalty = 8.0
freeze = False

# get from script instead - trying out grid search script
parser = argparse.ArgumentParser()
parser.add_argument("--name", type=str, default="shirt")
parser.add_argument("--learning_rate", type=float, default=0.0005)
parser.add_argument("--epochs", type=int, default=100)
parser.add_argument("--n_stop", type=int, default=35)
parser.add_argument("--batch_size", type=int, default=8)
parser.add_argument("--penalty", type=float, default=8.0)
#parser.add_argument("--freeze", type=bool, default=False)

args = parser.parse_args()

# Assign hyperparameters dynamically
name = args.name
learning_rate = args.learning_rate
epochs = args.epochs
n_stop = args.n_stop
batch_size = args.batch_size
penalty = args.penalty






# def main():
#     # Create an ArgumentParser object
#     parser = argparse.ArgumentParser(description="A script that takes command-line parameters for model training.")
#     parser.add_argument('--name', type=str, default='skirt', help='The name of the model or project')
#     parser.add_argument('--learning_rate', type=float, default=0.0005, help='The learning rate for the model')
#     parser.add_argument('--penalty', type=float, default=5.0, help='Penalty (regularization) parameter')
#     args = parser.parse_args()

#     name = args.name
#     learning_rate = args.learning_rate
#     penalty = args.penalty

#     print(f"Model Name: {name}")
#     print(f"Learning Rate: {learning_rate}")
#     print(f"Penalty: {penalty}")

# if __name__ == "__main__":
#     main()
    
    
"""Get dataset info"""

component = component_data.get(name, "Item not found")
data_path = component["data_path"]
csv_path = component["csv_path"]

n_attributes = component["n_attributes"]
attribute_names = component["attribute_names"]
lb = component["attribute_lowerbounds"]
ub = component["attribute_upperbounds"]
defaults = component["attribute_defaults"]

train_info = get_training_info(name, "vit", learning_rate, epochs, n_stop, batch_size, penalty, attribute_names)
outfilename = "base_regression_vit-" + name + "-" + str(learning_rate) + "-" + str(epochs) + "-" + str(n_stop) + "-" + str(batch_size) + "-" + "penalty" + str(int(penalty))
if freeze == True:
    outfilename += "-freeze"
print("outfilename")
outfilename += ".png"
# outfilename = "DEBUG.png"

""" Processing csv file"""

labels_df = pd.read_csv(csv_path)
num_columns = labels_df.shape[1]
num_attributes = num_columns - 1
assert(n_attributes == num_attributes)
print("Number of attributes: ", num_attributes)
print(labels_df.head())

""" Creating the datasets"""
train_ratio = 0.7
validation_ratio = 0.1
test_ratio = 0.2

data_n = len([f for f in os.listdir(data_path) if os.path.isfile(os.path.join(data_path, f))])
train_n = round(data_n* train_ratio)
val_n = round(data_n* validation_ratio)
test_n = data_n - train_n - val_n

print("Number of images: ", data_n)
print("Train: ", train_n)
print("Validation: ", val_n)
print("Test: ", test_n)

train_labels_set, val_labels_set, test_labels_set = np.split(labels_df.sample(frac=1), [int(.6*data_n), int(.8*data_n)])

"""Dataloaders"""

train_transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ColorJitter(brightness=0.3, contrast=0.5, saturation=0.3, hue=0.3),
        transforms.Grayscale(num_output_channels=1),
        transforms.GaussianBlur(kernel_size=5, sigma=(0.1, 2.0)),
        # transforms.Normalize([0.485, 0.456, 0.406],
        #                      [0.229, 0.224, 0.225])  # Imagenet standards
    ])

# get three functions
normalize_fn, reverse_fn = create_normalization_fns(ub, lb)

#Tamim - adding this as a safety check:
if reverse_fn is None:
    print("WARNING: reverse_fn is None. Setting a default function.")
    def reverse_fn(x):
        return x  # Identity function, replace if needed.

train_image_set = LandmarksDataset(dataframe = train_labels_set,
                                    root_dir=data_path,
                                    normalize=normalize_fn,
                                    transform=train_transform,
                                    )
train_loader = torch.utils.data.DataLoader(train_image_set, batch_size=batch_size, shuffle=True)
val_image_set = LandmarksDataset(dataframe = val_labels_set,
                                  root_dir=data_path,
                                  normalize=normalize_fn,
                                  transform=train_transform)
val_loader = torch.utils.data.DataLoader(val_image_set, batch_size=batch_size, shuffle=True)
test_image_set = LandmarksDataset(dataframe = test_labels_set,
                                  root_dir=data_path,
                                  normalize=normalize_fn,
                                  transform=train_transform)
test_loader = torch.utils.data.DataLoader(test_image_set, batch_size=batch_size, shuffle=True)



train_features, train_labels = next(iter(val_loader))

# def display_training_set():
show_training_set = False
if show_training_set:
    fig, axes = plt.subplots(4, 2, figsize=(9, 9))
    for i, ax in enumerate(axes.flat):
        if i >= 8:
            break

        img = train_features[i]
        label = reverse_fn(np.array(train_labels[i]))
        image_tensor = img.permute(1, 2, 0) * 255
        image_tensor = image_tensor.type(torch.uint8)
        ax.imshow(np.array(image_tensor), cmap="gray")
        ax.set_title(f"{label}", fontsize=10)  # Display label

    plt.tight_layout()
    plt.savefig("test.png")


'''
MODEL
'''
model = models.vit_b_16(weights='DEFAULT')

# do not freeze parameters since it was trained on imagenet,
for param in model.parameters():
    param.requires_grad = freeze

n_inputs = model.heads.head.in_features
model.heads = nn.Sequential(
    nn.Linear(n_inputs, num_attributes, bias=True),
    nn.Sigmoid() # Restrict to (0,1)
    # ClippedReLU()   
)

# take in grayscale
model.conv_proj = nn.Conv2d(1, 768, kernel_size=(16, 16), stride=(16, 16))

model = model.to('cuda')

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
# criterion = nn.MSELoss()
criterion = getWeightedMSELossCriterion(default_values=defaults, weight=penalty)

model, train_loss, valid_loss = train_multi(model,criterion,optimizer,train_loader,val_loader, 
                                            n_stop, epochs)

# test with the regular MSELoss
criterion = nn.MSELoss()
test_errors = test_multi(model,test_loader, criterion, reverse_fn, outfilename, train_info)
print("test errors:", test_errors)

torch.save(model.state_dict(), f"{name}-{learning_rate}-fine_tuned_vit.pth")

print("train loss:", train_loss)
print("valid_loss:", valid_loss)
#print(f"train_loss: {train_loss[-1]}, valid_loss: {valid_loss[-1]}, test_loss: {test_errors['MSE']}")